[package]
name = "hello-wasm"
version = "0.1.0"
description = "A sample project with block wasm"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]
